### ISSUE TITLE
Don't complain about missing route_master if route is a roundtrip

### ISSUE THREAD

**Issue by An-dz** [osm-fr/osmose-backend#1015]
For **item 1260 class 4**, that checks if the route has a *route_master* relation, I think it should not report if the route is a roundtrip.

According to the [OSM wiki](https://wiki.openstreetmap.org/wiki/Buses#Step_3_-_Create_a_route_master_relation) a *route_master* is not necessary if there are no variations and it's a roundtrip.

The only problem is if there are two variations of the same roundtrip route, in this case a new check should consider if the ref number and/or the name are the same and then report that one should be removed (duplicate) or both joined in a *route_master* relation.

Link to a route that is a roundtrip and has no variants:

https://osmose.openstreetmap.fr/en/error/209f5789-c2d1-8cc3-1888-9d60882de987

**Comment by frodrigo** [comment]
cc @nlehuby

**Comment by nlehuby** [comment]
I've never heard about this roundtrip rule.
Personally, I would still add this roundtrip route relation into a route_master relation: if we have route_master but only in some cases, some basic operations such as counting the number of bus lines in a city can become challenging.

**Comment by CAM-Gerlach** [comment]
Revisiting this in 2026--I'm a mapper starting to upgrade the bus routes in my town (Blacksburg, VA), most if not almost all of which are roundtrips in some form, to PTv2 and fixing the bevy of associated Osmose warnings following the latest community wiki guidance. Just to be clear up front, I have no particular preference for whether or not to add a route master in these cases, I just want to make sure I'm following the current accepted best practice here, and despite seeing guidance suggesting I shouldn't, I wanted to make sure before I did so.

As such, I searched far and wide to see whether I should still creating a route master for a roundtrip route and duplicating the relevant tags on it. However, in various places I looked on the wiki that addressed the issue, the current guidance stated that a route master was not needed for a roundtrip route, e.g.

* On the [main Public Transport article](https://wiki.openstreetmap.org/wiki/Public_transport#Route_master_relations):

  > If only one relation is used to map the public transport route, which can happen if the route completes a round trip, no route master is needed. 

* On the [Buses article](https://wiki.openstreetmap.org/wiki/Buses#Step_3_-_Create_a_route_master_relation), it states in bold at the top of the route master section:

  > **No route master relation is needed if the bus route is a loop, and therefore only mapped with one relation (and given the tag [roundtrip](https://wiki.openstreetmap.org/wiki/Key:roundtrip)=[yes](https://wiki.openstreetmap.org/wiki/Tag:roundtrip%3Dyes)).**

Given the guidance seemed to state quite unequivocally that there was no need to add one, I didn't do so.

Does this not in fact represent community censuses/practice, and should be revised (and I should add route masters accordingly)? Or is Osmose the one that should be updated here? Again, I have no particular stake here, I just want to make sure my PTv2 mapping reflects the best current practices.

**Comment by nlehuby** [comment]
I'm rediscovering this old github issue, and with it this rule!

It doesn't seem to appear on any French-language pages. And I can't find any trace of it in the[ initial ptv2 proposal](https://wiki.openstreetmap.org/w/index.php?oldid=625726#Route_Master) either, so I don't really see the legitimacy of this restriction.
Maybe it's a regional rule ?

Moreover,  it doesn't seem very relevant to me: the fact that a line is circular doesn't necessarily mean that it has a single route. Here is a counterexample, for example https://jungle-bus.github.io/unroll/route.html?line=15644002&qa=yes

And if we decide we have to use route_master sometimes but not always, it really complicates the reuse of data. 
The route_master relation indicates a line, and the route relation indicates a regular trip; these are different objects, so it feels normal for there to be two distinct objects in OSM, even if there is only one trip pattern.

**Comment by CAM-Gerlach** [comment]
Thanks for your quick response! Given that, I've gone ahead and [added route masters to the roundtrip routes I've added recently](https://www.openstreetmap.org/changeset/179600081).

> It doesn't seem to appear on any French-language pages. And I can't find any trace of it in the[ initial ptv2 proposal](https://wiki.openstreetmap.org/w/index.php?oldid=625726#Route_Master) either, so I don't really see the legitimacy of this restriction.
Maybe it's a regional rule ?

Yeah, AFAIK it wasn't in the original PTv2 proposal and was rather one of the additions/simplifications in current PT practice that have evolved more organically over the years, in tandem with the several formal PTv2 simplification proposals. I'm not sure I'd call it not "legitimate" as much evolution of OSM practice is organic over time as much as via formal approved proposals, but I'm guessing that's probably just a translation thing. However, while I see a lot of discussion on `roundtrip` and based on wide usage it has been granted "de-facto" status, at least with some preliminary searching I couldn't find a lot on the implications for not requiring a route master, so I'm not sure how that determination was made.

> Moreover, it doesn't seem very relevant to me: the fact that a line is circular doesn't necessarily mean that it has a single route. Here is a counterexample, for example [jungle-bus.github.io/unroll/route.html?line=15644002&qa=yes](https://jungle-bus.github.io/unroll/route.html?line=15644002&qa=yes)

Yeah, that's a good point--its not the case in my town, but I imagine many roundtrip lines might have variants in both directions like that, as well as other types of route variations. I'm pretty strongly in favor of being explicit and avoiding cases where it is ambiguous whether something doesn't have something, or merely wasn't checked/mapped/tagged properly yet.

> And if we decide we have to use route_master sometimes but not always, it really complicates the reuse of data.

Yeah, and likewise I'm also in favor of consistency across cases like this, so that makes sense to me 👍 

Perhaps a discussion should be started on the OSM forum to gather feedback on this and potentially revise the wiki accordingly?

**Comment by nlehuby** [comment]
> Perhaps a discussion should be started on the OSM forum to gather feedback on this and potentially revise the wiki accordingly?

Yes, that would be great. Do you want to start this discussion ?

**Comment by CAM-Gerlach** [comment]
Sure, I could, although if you are able to start it and I chime in it might be better, as you have far more expertise, experience, credibility and authority when it comes to public transport mapping than a regular mapper like me (as much as almost any mapper, I'm sure) :)
