### ISSUE TITLE
Sport tag and multi-values seen as incorrect value (3040)

### ISSUE THREAD

**Issue by imagoiq** [osm-fr/osmose-backend#1052]
Hi,

I have two examples of sport field where it seems that there is a false positive.

`sport=` should allow the usage of multi value separated with semi-colons as it seems here in the backend: 
https://github.com/osm-fr/osmose-backend/blob/cb5e3a1f387851f4ac424a612c9eaddcf4685637/plugins/TagFix_MultipleValue.py#L48

Here are the two elements with an error: 
https://osmose.openstreetmap.fr/en/error/e96e1670-b918-9bd5-58ea-37eb5ed94ea7
https://osmose.openstreetmap.fr/en/error/f986059d-7b86-605d-fb1a-946eeb3f2abd

Maybe it is because in both cases, the tag contains a sport with a dash.

**Comment by frodrigo** [comment]
On each detail pages you can find a link to the source code. In your case it is 
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_BadValue.py
and not TagFix_MultipleValue.py

Yes it is because of dash. Exception have to be added in white list https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_BadValue.py#L70

But, not sure about the wiki, "jiu-jitsu" (not the most english current way to write it I guess) is the only sport with a dash. And loosely added on the wiki.

https://en.wikipedia.org/wiki/Jujutsu

**Comment by frodrigo** [comment]
Reopen if required.
