### ISSUE TITLE
Move "invalid opening hours" to high priority

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1142]
http://osmose.openstreetmap.fr/en/map/#zoom=10&lat=50.2814&lon=19.134&item=3250&level=1%2C2%2C3&tags=&fixable=

Unparseable opening hours are very often remotely fixable, and case where human input is highly useful and tag itself is in actual use.

Note also that `opening_hours` values that can not be parsed will not be resurveyed by StreetComplete

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/blob/master/plugins/TagFix_Opening_Hours.py#L38

But there are already on level 3, the lower one.

**Comment by matkoniecz** [comment]
So it would be changing ` level = 3` to ` level = 1`, right?

**Comment by frodrigo** [comment]
I personally think OH are not first citizen class data in OSM.

cc @dfaure

**Comment by Marc-marc-marc** [comment]
level 1 seems much too high to me, most tools don't use it.
level 2 might be more suitable than level 3.
For SC, I think on the contrary that it would be very useful to have a "so erroneous that it is impossible to correct it automatically", please make a note+photo" quest in order to be able to correct them.
it would even be very nice if SC could connect to osmose to retrieve the error list and the existence of an automatic fix or not, in order to have a central code that could be improved instead of having an incomplete part of the solution in each tool.

**Comment by dfaure-kdab** [comment]
I am too young in the OSM community to have any overview on the priority system in Osmose.

I agree that opening hours are fixable online. Sometimes by just looking at the attribute itself (I do this regularly), sometimes by some online searching for the opening hours as advertised by the shop (etc.).

BTW the link given by the original poster shows a map in Poland but nothing on it. Is there an issue with sharing osmose links? Is it just very slow?

**Comment by matkoniecz** [comment]
> it would even be very nice if SC could connect to osmose to retrieve the error list and the existence of an automatic fix or not

The problem is that SC has solely tasks that can be done by someone with zero knowledge about OSM tagging, with no exposure to actual tag - with an acceptable error rate.
