### ISSUE TITLE
"railway=construction without construction:railway" is quite pointless.

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#1159]
original title: Create new category or remove tasks that are fully bottable

For example "railway=construction without construction:railway" is quite pointless.

If that would be an useful improvement (in my opinion it is not) then proper way of implementing this would be to run bot or mass edit with JOSM/level0 ( for someone planning that - please be aware of https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct ).

Having that in Osmose seems to be  a pointless and done because there is no actual support for such change - and presence of such rules seems to be a main drawback of Osmose, my main worry of promoting it is that I also promote such weird retagging idea (this rule comes from openrailwaymap.validator.mapcss).

Would it be possible to get rid of it or at least move to some separate special category?

http://osmose.openstreetmap.fr/en/map/#zoom=17&lat=50.049871&lon=19.956482&item=xxxx&level=3&tags=&fixable=&issue_uuid=89782a8f-c383-3b29-6a60-362dcf9d9178
http://osmose.openstreetmap.fr/en/error/89782a8f-c383-3b29-6a60-362dcf9d9178

**Comment by frodrigo** [comment]
1. We can black list rule from external MapCSS https://github.com/osm-fr/osmose-backend/blob/master/mapcss/item_map.py#L83
2. We can add more osmose tags to osmose classes, feel free to suggest a new one for bot-doable an then PR to add it.
3. An exclusion filter must be add on the frontend

**Comment by matkoniecz** [comment]
Is "subclass_blacklist" referring to 9015027 in http://osmose.openstreetmap.fr/en/error/89782a8f-c383-3b29-6a60-362dcf9d9178

Is fix as simple as adding 9015027 to new list for https://github.com/osm-fr/osmose-backend/blob/master/mapcss/item_map.py#L152 that would be formatted like https://github.com/osm-fr/osmose-backend/blob/master/mapcss/item_map.py#L108 ?

**Comment by frodrigo** [comment]
Yes

**Comment by frodrigo** [comment]
Yes, Then the cdoe from the MapCSS should be regenerated.

**Comment by Bibi56** [comment]
you can build a railway or a train station, what is wrong asking if a rail or a building is being build? At some point you'll add the nature of a railway infrastructure, won't you? Similar to all railway prefix. Yes due to the nature (linear or not) it can be largely automated. If you want to crate a bot, I'm fine with that (if allowed by the community of course). Another possibility would when we correct a linear tag, that Osmose proposes to extend the change to the similar connected ways. I think about path with foot=yes cycle=yes missing a segregated=*.

**Comment by frodrigo** [comment]
Keep this rule.
