### ISSUE TITLE
All the streets are reported missing in Toulouse

### ISSUE THREAD

**Issue by Art-Penteur** [osm-fr/osmose-backend#122]
For a few days now the test "routes" in Osmose reports all the streets  as "route potentiellement manquante".

![osmose_toute_rues_manquantes_toulouse](https://cloud.githubusercontent.com/assets/7870824/17079144/9138d9ee-5107-11e6-920f-1248f7966c07.png)

**Comment by frodrigo** [comment]
I think the issue is for France. @cquest can you check your submits.

http://osmose.openstreetmap.fr/fr/errors/?item=7170
http://osmose.openstreetmap.fr/fr/errors/graph.png?item=7170

http://osmose.openstreetmap.fr/fr/errors/?source=14708&item=7170&class=2
http://osmose.openstreetmap.fr/fr/errors/graph.png?source=14708&item=7170&class=2

**Comment by cquest** [comment]
C'est la classe 30 qui pose problème et ça ne semble pas nouveau: http://osmose.openstreetmap.fr/fr/errors/graph.png?item=7170&class=30

Etrange, ce n'est pas systématique sur la France entière... je fouille...

**Comment by cquest** [comment]
Erreur corrigée... environ 30000 faux-positifs de moins :)

http://osmose.openstreetmap.fr/fr/map/#item=7170&class=30&zoom=17&lat=43.607753&lon=1.44396&layer=Mapnik&overlays=FFFFFFFFFFFFFFFFFFFFT

**Comment by Art-Penteur** [comment]
Tout ne semble pas vraiment réglé : J'ai du mal à comprendre pourquoi je devrais modifier la "Rue de Gap" en "Rue de Gap"
![erreur_osmose_incomprehensible_20160918](https://cloud.githubusercontent.com/assets/7870824/18613721/87306e44-7d80-11e6-9fce-0309bac6a754.png)
