### ISSUE TITLE
The stops may not be in the right order 1260/11

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1262]
This new analyser raise may false positive

EG https://www.openstreetmap.org/relation/2422779
Only two stops, the first is good, the last raise an issue
http://osmose.openstreetmap.fr/fr/error/65d681fc-ac08-4609-b04f-eb9b11f9a3d6

**Comment by nlehuby** [comment]
I think it's because the offset (`ST_OffsetCurve`) is not applied any more:
https://github.com/osm-fr/osmose-backend/pull/1254/files#diff-d73bbaa10a217bc33339087e3143f8337f95ca9e0bfcdccf87f022644eabd708R478 (and 490)

The offset reverses the linestring which is why we have to order desc when computing the order of the projected stop.
