### ISSUE TITLE
Error trying "Running on a single country"

### ISSUE THREAD

**Issue by rikMaz** [osm-fr/osmose-backend#1273]
Hello,

i am getting the error: 

`No such file or directory: '/opt/osmose-backend/modules/../dictionaries/fr/reaccentue.pz'`

After i built the docker image and executed this command:

`docker-compose --project-name monaco run --rm backend ./osmose_run.py --country=monaco`

Can anyone tell me how to solve this problem?

Thanks in advance.

**Comment by frodrigo** [comment]
Path look good. Check about this directory https://github.com/osm-fr/osmose-backend/tree/master/dictionaries/fr

**Comment by rikardomarenzzi** [comment]
Thank you for the quick reply!
I have the directory. 
How do I get this directory into the modules folder so that the directory will be found?

**Comment by frodrigo** [comment]
`..` means parent directory, so it is expected in the root directory of the project. Are you running in an other platform than linux ?

**Comment by rikardomarenzzi** [comment]
I am using a mac with macOS Big Sur.
I haven't changed the dockerfiles or the rest of the repositiry.

**Comment by frodrigo** [comment]
It is not be tested recently on MaOS, it may have issues.

Check the path front within the docker container. Something like that:
```
docker-compose run --rm backend bash
ls /opt/osmose-backend/modules/../dictionaries/fr/reaccentue.pz
```

**Comment by frodrigo** [comment]
It is now ok for you ?

**Comment by kidhanis** [comment]
@frodrigo, I'm encountering this issue as well, using macOS.

The problem is that the macOS filesystems are case insensitive by default, so `dictionaries/fr` and `dictionaries/FR` are considered the same directory. When I clone `osmose-backend` to my computer, the `dictionaries/FR` directory ends up with ten files, which are the five files in [dictionaries/FR](https://github.com/osm-fr/osmose-backend/tree/f2580027b34246684ba3009360d05747e0b3960e/dictionaries/FR) plus the five files originally from [dictionaries/fr](https://github.com/osm-fr/osmose-backend/tree/f2580027b34246684ba3009360d05747e0b3960e/dictionaries/fr).

I tested the following inside the container to confirm:

```shellsession
$ ls /opt/osmose-backend/modules/../dictionaries/fr/reaccentue.pz
ls: cannot access '/opt/osmose-backend/modules/../dictionaries/fr/reaccentue.pz': No such file or directory
$ ls /opt/osmose-backend/modules/../dictionaries/fr/
ls: cannot access '/opt/osmose-backend/modules/../dictionaries/fr/': No such file or directory
$ ls /opt/osmose-backend/modules/../dictionaries/FR/reaccentue.pz
/opt/osmose-backend/modules/../dictionaries/FR/reaccentue.pz
```

**Comment by frodrigo** [comment]
We already have seen this issue in plugin directory and replaced 'FR' by 'Lang_fr'.

**Comment by frodrigo** [comment]
Fixed
