### ISSUE TITLE
Freshness of "Highway intersecting small/large water piece" in spain_castilla_y_leon

### ISSUE THREAD

**Issue by Crashillo** [osm-fr/osmose-backend#1301]
Since a couple of days I'm noticing there's no updates on the `item=1070&class=4,5`.

For instance, most of the markers you can find in this bbox http://osmose.openstreetmap.fr/es/map/#username=Hugoren%20Martinako&item=1070&class=4%2C5&zoom=11&lat=42.9503&lon=-5.1588&level=1%2C2%2C3 have been already fixed one week ago. However, the tooltip says the issue was reported yesterday and the update_matrix displays an age < 1 for the Osmosis_Highway_VS_Building analyzer

How's this possible? Are not all classes (of an item) updated at the same time?

**Comment by frodrigo** [comment]
All classes of a source (aka country/area) are updated at the same time.
http://osmose.openstreetmap.fr/es/issues/open?country=spain_castilla_y_leon&item=1070&source=&class=4&username=&bbox=

OSM extract is up to date.
https://buildbot.osmose.openstreetmap.fr/#/builders/236/builds/320/steps/1/logs/stdio (#173)

The extract look ok (not corrupted), and the contain the new bridge 82224058 and the edited highway 805343918 in version #2.

cc @jocelynj

**Comment by Crashillo** [comment]
Notified also in *spain_galicia*

**Comment by Crashillo** [comment]
Notified also for item 5080 in _Castilla y León_. It looks like the comparison is being done against an outdated extract.

http://osmose.openstreetmap.fr/en/map/#item=5080&zoom=17&lat=42.328434&lon=-5.993289&level=1&tags=&fixable=&issue_uuid=2f5e14da-c864-69f3-a280-a9562b9de539

These errors show [this way](https://www.openstreetmap.org/way/520976111)'s name as _Calle La Calzada_, nevertheless, such name was changed a week ago in favour of _Calle la Calzada_ (lowercase articles).

**Comment by frodrigo** [comment]
Sorry for not looking in details at it before, but lake of time.
Now I am away of computer for holidays... in Castilla y León.

**Comment by Crashillo** [comment]
It looks like it has been fixed. No idea why.

> Now I am away of computer for holidays... in Castilla y León.

I've seen some notes around... :grin:

**Comment by frodrigo** [comment]
Strange because the graph doe not have variation
http://osmose.openstreetmap.fr/es/issues/open?country=spain_castilla_y_leon&item=1070&source=&class=4&username=&bbox=
http://osmose.openstreetmap.fr/es/issues/graph.png?country=spain_castilla_y_leon&item=1070&source=&class=4&username=&bbox=

http://osmose.openstreetmap.fr/fr/issues/open?country=spain_castilla_y_leon&source=&class=&useDevItem=all&username=&bbox=&item=5080
http://osmose.openstreetmap.fr/fr/issues/graph.png?country=spain_castilla_y_leon&source=&class=&useDevItem=all&username=&bbox=&item=5080

http://osmose.openstreetmap.fr/en/issues/open?item=xxxx&source=13307
http://osmose.openstreetmap.fr/en/issues/graph.png?item=xxxx&source=13307

I close it. I have no idea what may append. Comment it or open a new issue if necessary.

**Comment by Crashillo** [comment]
Still happening.

I noticed a bunch of odd things, look at the beneath picture:
- The issue was fixed several days ago, but the reported date is today, Aug 24th
- Even the background tile is showing a bridge, nonexistent prior to the actual issue (the fix was about adding such bridge)
- The update matrix values are all below 1 (i.e. less than 24h from the last execution)
- The _Delay_ menu (between help & user dropdowns) shows 14h at the time of this comment. Is this the real time from the last execution? Anyway, it's also updated.

![imagen](https://user-images.githubusercontent.com/817526/130679449-db259607-56d2-42b5-898d-0ccabbd12ac3.png)

So, there's still something _caching_ issues. One bet could be the OSM extract is used, perhaps outdated. Another bet is about the database, like it's saving/caching the issues somehow.

**Comment by JorgeSanzS** [comment]
Same with http://osmose.openstreetmap.fr/es/issues/open?source=13793&item=7040&class=4

**Comment by frodrigo** [comment]
Reported on
- [ ] item=1070, class=4,5, analyser_osmosis_highway_vs_building.py
- [ ] item=0, class=?
- [ ] item=5080, class=1, probably same as #1379
- [ ] item=7040, class=4 analyser_osmosis_powerline.py

**Comment by frodrigo** [comment]
analyser_osmosis_powerline.py item=7040, class=4 issue in the code of the analyse with differential update mode, fixed, update in progress.

**Comment by frodrigo** [comment]
A global fix on how markers are updated, has been released.
The data update is still processing for hours, and maybe days for some the areas of the world.

This issue is based on accumulation of non removed marker after the issues on the osm data are fixed when using partial analyses of new data from osm.

The release of this fix has as side effect to do an automatic full recheck of the data and vacuums differential markers. So all ghost markers will be removed. But it is only a side effect and not the result of really fixing the issue. The ghost markers could come back if the bug if not fully fixed.

Please report if you see something similar in the future.

**Comment by Crashillo** [comment]
Ok, now I noticed my surroundings to be wiped. Hence, I just fixed a few more issues and I'll come back later on this in order to check whether is working or not 🤞

**Comment by Crashillo** [comment]
I was skimming this along these days a couple of times, fixing some and waiting for the updates. Everything seems back to normal :+1: so, as for me, it's fixed. Reopen if need

**Comment by frodrigo** [comment]
Good news ! Thank you all for reports and waiting for the fix.
