### ISSUE TITLE
Wrong detection of conflict on lanes number?

### ISSUE THREAD

**Issue by SomeMichael** [osm-fr/osmose-backend#1309]
This [concerns](https://osmose.openstreetmap.fr/en/issue/41261d16-c28f-02f9-c13d-03a8f5d5819d) ([way](https://www.openstreetmap.org/way/4067196) Version 33)

osmose reports:
`(lanes(lanes:*:backward)=2) - (non fullwidth=0) != (lanes(access:lanes:backward)=2) - (non fullwidth=1)`

But from my point of view that's wrong. I guess osmose just checks _access:lanes:backward=no|yes_. That would make the first lane _non fullwidth_. But thers's also a _psv:lanes:backward=designated|yes_. Therefore the lane should be fullwidth, isn't it?

Thanks for your help!

**Comment by frodrigo** [comment]
No, all lanes are taken in account.

**Comment by Strubbl** [comment]
lanes:psv* are not counted, another example is https://osmose.openstreetmap.fr/en/issue/de41c950-22f9-0078-a2bf-a378988438dd

**Comment by BalooUriza** [comment]
Kinda wondering if assuming "full width" is a bad guess.  This check will always trigger on designated bike lanes that can be used by cars, too.  I also question whether this is even a reasonable check, given that excluding narrow bicycle lanes from counts makes validating and consuming the data way more difficult than it needs to be versus just counting lanes as lanes.

**Comment by Famlam** [comment]
This issue was fixed with https://github.com/osm-fr/osmose-backend/commit/ec95a440122bf75235f40d791f83921951463672 last month.

Note that the [other issue reported](https://osmose.openstreetmap.fr/en/issue/de41c950-22f9-0078-a2bf-a378988438dd) is correct, see for instance the wiki of [lanes:psv](https://wiki.openstreetmap.org/w/index.php?title=Key:lanes:psv) . The psv lane should be part of the overall lanes count, so `lanes:backward = 2` if there's a regular lane and a designated psv lane in the backward direction.
