### ISSUE TITLE
BD Topo saddle

### ISSUE THREAD

**Issue by Hades1503** [osm-fr/osmose-backend#1356]
According to the OSM wiki, the passes are tagged "mountain_pass" if a road/trail passes at the same place, otherwise it is the "saddle" tag. 
The altitude of saddle is missing.

Is it possible to add this condition in Osmose?

**Comment by archie83** [comment]
That is not what I understand after reading [https://wiki.openstreetmap.org/wiki/Tag:natural%3Dsaddle](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dsaddle). Saddles are really the lowest points in a ridge, while mountain passes are the lowest points on the roads, that may be higher than the saddles.

Altitudes are not present in the BD TOPO, so it is not possible to propose them.

**Comment by Hades1503** [comment]
Names of passes without the altitude is not very useful ...

**Comment by archie83** [comment]
I think the presence of a saddle and the name are at least as important as the elevation.

Anyway, if you want to add the elevation, you can use the IGN geoservice "Calcul altimétrique":
https://geoservices.ign.fr/documentation/services/api-et-services-ogc/calcul-altimetrique-rest#1870

Example (Col de la Cayolle):
In JOSM, select the node containing the saddle, then click on "Edit", "Copy Coordinates" to get the coordinates.

Then call the IGN service:
https://wxs.ign.fr/essentiels/alti/rest/elevation.json?lon=6.7439734&lat=44.259142&zonly=true

You'll get this result:
2326.71

It is not possible to automatize this method in Osmose, because the locations of saddles and summits are not very precise in the BD TOPO (sometimes more than 50 meters from the real position), so it is mandatory to adjust the position before looking for the elevation.

**Comment by frodrigo** [comment]
https://github.com/osm-fr/osmose-backend/commit/ad325cc5e25f58b6aed6e890489730a68584760b

**Comment by archie83** [comment]
ad325cc is not related to this issue.

**Comment by frodrigo** [comment]
I close.
Add comment, on what need to be changed in the Osmose configuration, then I will reopen it.
