### ISSUE TITLE
Marker keeps getting reported on 'gone' objects

### ISSUE THREAD

**Issue by WK-GiHu** [osm-fr/osmose-backend#144]
How does OSMOSE handle 'gone' objects?

The following marker will show again.
I clicked 'corrected'.
1150 Area intersection landuse
http://osmose.openstreetmap.fr/de/error/8213891322

The Correction was done, using JOSM 'Merge intersecting areas'.
Therefore the nodes of the 'gone' areas merged into way382290836, 
and the 2 useless objects deleted.

Rawedit reports both 'marker.elems' as 'gone'.

**Comment by jocelynj** [comment]
I've seen some extracts used by osmose that contained OSM objects that were removed. I will regenerate them, which should remove this error.

**Comment by WK-GiHu** [comment]
Thanks for the correction. 
But this problem seems similar to the problems # 143 and # 128.
In addition, my example is only one of several in which markers appear repeatedly. 

This behavior should be basically eliminated. 
Can you answer my initial question?

**Comment by jocelynj** [comment]
When you are clicking on "done" on a popup, osmose stores this entry in its database, and won't show this error for at least 7 days. If this error is still present again on country extract, then error will re-appear.
If you fix an error without clicking on "done", then it is the next time that this country is analysed, and reports error are fixed that error will disappear from map.

Now, the issue here, and at least another github issue, is that the extract generation is not perfect, but I couldn't find why it is failing. It is using https://github.com/jocelynj/osm/tree/master/osc_modif and a complete database to generate country diffs from planet diff. Then extracts are updated once per day.

If you want to help, some testcases would be very useful to check country diff generation (two osm extracts with changes inside, outside, or crossing a polygon boundary)

**Comment by WK-GiHu** [comment]
I looked at osc_modify.py and have any questions. 
I'll also need deeper explanation about "to generate diffs country from planet diff" and "inside, outside". 

If you agree, I open new Issues on  "https://github.com/jocelynj/osm/tree/master".

**Comment by jocelynj** [comment]
No problem to open issues on the other github repository.

I already looked several times at this logic, but a new eye is welcomed !
