### ISSUE TITLE
ref:mise values, required on Italian fuel station are all getting the absent or invalid flag

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1515]
Reported from https://github.com/osm-fr/osmose-backend/issues/1476#issuecomment-1212458351

ref:mise values, required on Italian fuel station are all getting the absent or invalid flag. Purple carpet bombing

http://osmose.openstreetmap.fr/en/issues/open?item=7250

A sudden change append http://osmose.openstreetmap.fr/en/issues/graph.png?item=7250

Values may be invalid from the OpenData source

cc @sekerob @fansanelli

**Comment by Famlam** [comment]
An example from the other issue: http://osmose.openstreetmap.fr/nl/issue/020a9361-cb39-3d8e-7f66-d0f668833de6 `ref:mise=4339`

**Comment by sekerob** [comment]
Caught in the act, verified and confiremed correct ref:mise 53317 but still flagged as wrong or missing ref:mise

https://osmose.openstreetmap.fr/en/map/#item=7250&zoom=17&lat=43.09705&lon=13.841845&level=3&tags=&fixable=

Could it be this has become sort of the catch all top rule, whatever is wrong, this signal kicks out. Is it the fuel, is it the addres, is it the operator, name of statio, what. These used to get highlighted in orange and green lines in the pop up box when clicking the pin but do not record having seen any of these since the issue began.

Anyway, not touched the pin but looking and adding various bits to the area while there with CS https://www.openstreetmap.org/edit?node=227529039#map=20/43.09699/13.84206. The data of the station checks with the MISE register which only updates once every trimestre, toward the last 2 weeks i.e. next register refresh expected mid September, 2022 as published by the Ministero dello Sviluppo Economico (Ministry of Economic Development9.

**Comment by frodrigo** [comment]
@fansanelli Fix deployed, but not working.

**Comment by fansanelli** [comment]
@frodrigo I think I found a logical problem, we check if  the prices got updated in last 30 days, but keep them in cache for 60. Can you confirm? I'll send a patch to reduce prices cache to 15 days

**Comment by frodrigo** [comment]
> @frodrigo I think I found a logical problem, we check if the prices got updated in last 30 days, but keep them in cache for 60. Can you confirm? I'll send a patch to reduce prices cache to 15 days

Yes, you are right.

**Comment by fansanelli** [comment]
PR opened. Would you mind to clean the cache in order to fix the production until the fix will be published?
Many thanks
Cheers
Francesco

**Comment by jocelynj** [comment]
I've just pushed the reduction of 15 days on OSM-FR backends.

Do we still need to clean cache, or will it be updated automatically?

**Comment by frodrigo** [comment]
> I've just pushed the reduction of 15 days on OSM-FR backends.
> 
> Do we still need to clean cache, or will it be updated automatically?

No, no need to clean the cache with the commit.

**Comment by frodrigo** [comment]
Thank @fansanelli we get back to previous issues level.

**Comment by sekerob** [comment]
The good news is, my Osmose Todo list today popped up 4 fresh fuel stations lines with need of updates, operator, fuel types, no moan at all on ref:mise.
