### ISSUE TITLE
Proposed integration of a closed shop

### ISSUE THREAD

**Issue by vmeurisse** [osm-fr/osmose-backend#1518]
Osmose is proposing me to integrate this shop that closed down in 2015:

name | Belle Optique | https://duckduckgo.com/?q=Belle Optique
-- | -- | --
ref:FR:SIRET | 43775835200045 | https://avis-situation-sirene.insee.fr/ListeSiretToEtab.action?form.nic=00045&form.siren=437758352
shop | optician |  
source | INSEE - 2022-06 |  

Status can be seen in the RCS data: https://www.infogreffe.fr/entreprise-societe/437758352-sarl-belle-optique-060105B000270000.html

This data is available under [open licence](https://www.etalab.gouv.fr/wp-content/uploads/2014/05/Licence_Ouverte.pdf) so it could be used to filter the dataset from sirene:
https://opendata.datainfogreffe.fr/explore/dataset/entreprises-radiees-2015/table/?q=SARL+BELLE+OPTIQUE&refine.greffe=ANTIBES

Note that a company can reopen so both [creations](https://opendata.datainfogreffe.fr/explore/?sort=modified&refine.theme=Immatriculations) and [removals](https://opendata.datainfogreffe.fr/explore/?sort=modified&refine.theme=Radiations) need to be processed to know the final status.

### Details of the Marker
key | value
-- | --
source | [414658](http://osmose.openstreetmap.fr/en/issues/open?item=xxxx&source=414658)
item | [8310](http://osmose.openstreetmap.fr/en/issues/open?item=8310)
class | [4707801](http://osmose.openstreetmap.fr/en/issues/open?item=8310&class=4707801)

**Comment by frodrigo** [comment]
Interesting. Help welcome.

cc @nlehuby

**Comment by nlehuby** [comment]
it's interesting indeed, thank you for this feedback, I didn't know about this data source.
But can we be sure that "radiation" necessarily implies that the physical office no longer exists? I understand that there can also be complex cases of "radiation" in case of company mergers or changes of shareholders ([for instance](https://www.infogreffe.fr/radiation/radiation-apres-transmission-patrimoine.html))

**Comment by frodrigo** [comment]
I think in most of that case the ref Siret Siren changes.
In all case, it should be a good way to avoid false positives.

**Comment by nlehuby** [comment]
I'm still struggling a bit with the concepts: apparently, a company can be "radiée" (unregistered) several times (for example this one 539452128, [3 times in 2012](https://opendata.datainfogreffe.fr/explore/dataset/entreprises-radiees-2012/table/?disjunctive.libelle&disjunctive.date&q=539452128) and again [once in 2014](https://opendata.datainfogreffe.fr/explore/dataset/entreprises-radiees-2014/table/?disjunctive.libelle&disjunctive.date&q=539452128). And it is listed as active on the [official business directory](https://annuaire-entreprises.data.gouv.fr/entreprise/539452128)) :thinking: 

But indeed, if it allows to eliminate some false positives, it is still relevant for us.

If I rework the Infogreffe datasets since 2012, extract a list of company to ignore and publish it as a community resource on data.gouv, (for instance [here](https://www.data.gouv.fr/fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/#community-resources)) will it be enough to fix the existing Osmose analysis @frodrigo ?

**Comment by frodrigo** [comment]
> I'm still struggling a bit with the concepts: apparently, a company can be "radiée" (unregistered) several times (for example this one 539452128, [3 times in 2012](https://opendata.datainfogreffe.fr/explore/dataset/entreprises-radiees-2012/table/?disjunctive.libelle&disjunctive.date&q=539452128) and again [once in 2014](https://opendata.datainfogreffe.fr/explore/dataset/entreprises-radiees-2014/table/?disjunctive.libelle&disjunctive.date&q=539452128). And it is listed as active on the [official business directory](https://annuaire-entreprises.data.gouv.fr/entreprise/539452128)) thinking

In your case it seams to to be linked to an address change, so it is "radiation d'un établissement", but not the whole company.

The data show only siren and not siret. siret is linked to address, siren not.

After "radiée" event, the company may exist in an other place. But since we do not have the siret, we have to use the address :-[ (and location based on the address) ?

> But indeed, if it allows to eliminate some false positives, it is still relevant for us.

I guess it may help on avoid false positives on moved shop, but not on definitively closed. To be verified.
If it is on moved shop, it may not be interesting on doing this work.
