### ISSUE TITLE
Unconnected roads false positives on border of regions

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#1524]
Item 1210
Class 2
[analyser_osmosis_highway_deadend.py](https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_highway_deadend.py)

Some false positives:
- http://osmose.openstreetmap.fr/nl/issue/ec838341-9afb-5724-feab-2ec451326e09 (but [way 7279505](https://www.openstreetmap.org/way/7279505) is clearly connected to ways [7279504](https://www.openstreetmap.org/way/7279504) and [929258603](https://www.openstreetmap.org/way/929258603))
- https://osmose.openstreetmap.fr/nl/issue/97993de7-469a-862c-fec2-a8157552a142 (but [way 504773533](https://www.openstreetmap.org/way/504773533) is clearly connected to ways [640155703](https://www.openstreetmap.org/way/640155703) and [490475029](https://www.openstreetmap.org/way/490475029))

Might have to do with both issues having a connection to a way on the border between two provinces?

**Comment by frodrigo** [comment]
Yes.
How it works ? It works by country / area (extract). But the extract have a buffer outside boundary limits. All issue outside the exact boundary are discarded.
It is how false positive should be hidden.

In you case the issue is linked to netherlands_utrecht and it is inside Utrecht territory, so all good at this point.

It looks ok in OSM.

The buffered polygon extract of Utrecht look OK
http://download.openstreetmap.fr/polygons/europe/netherlands/

Next step, check if the extract contains the connected way
http://download.openstreetmap.fr/extracts/europe/netherlands/

**Comment by Famlam** [comment]
> Next step, check if the extract contains the connected way

For the first example:
> http://osmose.openstreetmap.fr/nl/issue/ec838341-9afb-5724-feab-2ec451326e09 (but [way 7279505](https://www.openstreetmap.org/way/7279505) is clearly connected to ways [7279504](https://www.openstreetmap.org/way/7279504) and [929258603](https://www.openstreetmap.org/way/929258603))

The output of `osmconvert64-0.8.8p.exe utrecht.osm.pbf -b=4.86,51.95,4.90,51.96 --drop-nodes --drop-relations --drop-author --out-osm > utrecht.osm` on the Utrecht extract contains all three ways

**Comment by frodrigo** [comment]
@jocelynj can you check we have this ways on the extracts on the backed, please?

**Comment by frodrigo** [comment]
@Famlam the issues are gone, please can you re-check?

**Comment by Famlam** [comment]
Seems ok now :)
