### ISSUE TITLE
False-positive for tag 'ramp'

### ISSUE THREAD

**Issue by iiitomo** [osm-fr/osmose-backend#1575]
When detecting tag 'ramp', Osmose currently proposes to replace it by tag 'lamp'. 
See screenshot example below.
This is wrong as 'ramp' is a valid tag. See https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps

![osmose_error_suggestion_for_ramp](https://user-images.githubusercontent.com/58949423/192232159-f27fe0f5-fe40-436b-b8ba-55f7b391d62e.PNG)

**Comment by Famlam** [comment]
It seems a lot of people in your vicinity use the (undocumented) tag `lamp`. This'll probably get fixed as soon as #1483 is resolved

**Comment by frodrigo** [comment]
@iiitomo Please give a link rather than screenshot

https://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=51.179015&lon=6.441829&item=xxxx&level=1%2C2%2C3&tags=&class=

@iiitomo avoid to mark reported as false issue, when open a github issue - to keep a valid link and allow access all details quickly.

**Comment by frodrigo** [comment]
As undocumented tag with de facto quasi no-usage, yes it is good report from Osmose.

Note it is a typo check. So it suggest fixing a typo. There is also other controls, like deprecated or tagcleaner, to replace tags.
