### ISSUE TITLE
`rcn_region` is more common than `rwn_region`, is `rwn_region` a typo?

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1656]
Report by mail.

https://osmose.openstreetmap.fr/en/issue/290af61f-e94d-b046-54e7-11e6d2b078d8

`rcn_region` is more common than `rwn_region`, is `rwn_region` a typo?

cc @Famlam

**Comment by Famlam** [comment]
I can't find any definition of `XXn_region` on any wiki page about node networks, so this seems like a local non-documented invention?
As it's mostly used in NL, I'll drop a message in the forum/community later this week.

Anyway, if we want to whitelist (rather than create wiki pages or ignore it), what would you prefer? It seems only `rcn_region` is really in use, so whitelisting that one would fix all others too. On the other hand, I could also do it the same as https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_osmosis_tag_typo.py#L80 and fix potential future issues. 
See: https://taginfo.openstreetmap.org/search?q=_region for usage

**Comment by A67-A67** [comment]
It's certainly not a typo. rcn = regional cycle network, rwn = regional walking network. These abbrevations are commonly used on junction node networks, and have so for over ten years. 

The abbreviations I know of are:
- rcn = regional cycle network
- rhn = regional horse riding network
- rin = regional inline skating network
- rmn = regional motorboat network
- rpn = regional paddling network
- rwn = regional walking network

The most common use is in the tags [rcn_ref](https://wiki.openstreetmap.org/wiki/Key:rcn_ref), [rwn_ref](https://wiki.openstreetmap.org/wiki/Key:rwn_ref) and similar ones for the junction nodes and [network:rcn](https://wiki.openstreetmap.org/wiki/Tag:network%3Drcn), [network:rwn](https://wiki.openstreetmap.org/wiki/Tag:network%3Drwn) and similar ones for the routes between junction nodes.

The region-tags are a bit redundant, as they are for the name of the network. These can also be found from the network relation these nodes are added to. But they are certainly not typos.

**Comment by Famlam** [comment]
But is `**n_region` documented somewhere, and thus no warning should be given as it's an existing tag? (Note: the first `r` can also be `n`, `i` or `l` if it's a desired tag). Because if it's an undocumented, redundant and unwanted tag without meaning, I don't mind about false positives. Hence I started the discussion.

**Comment by A67-A67** [comment]
If I look for example to [this usage](https://www.openstreetmap.org/node/481331022) of `rwn_region`, it is used for the walking network Vlaamse Ardennen, not a cycling network called Vlaamse Ardennen. So `rwn_region` is not a typo here and changing it to  `rcn_region` is clearly wrong.

**Comment by frodrigo** [comment]
> If I look for example to [this usage](https://www.openstreetmap.org/node/481331022) of `rwn_region`, it is used for the walking network Vlaamse Ardennen, not a cycling network called Vlaamse Ardennen. So `rwn_region` is not a typo here and changing it to `rcn_region` is clearly wrong.

We are not arguing about the report is a typo or not. But as we does not support not existing  tags, not documented nor heavy usage.

We can exclude from typo report tags, but the tag have to be well know.

**Comment by Famlam** [comment]
Based on https://community.openstreetmap.org/t/de-sleutel-n-region/5728/8 the tag will be discarded, which has been done for a huge amount of them already: https://taginfo.openstreetmap.org/keys/rcn_region#chronology
So I think we can close this issue as wontfix?
