### ISSUE TITLE
height>min_height and building:levels>building:min_levels

### ISSUE THREAD

**Issue by ivanbranco** [osm-fr/osmose-backend#1842]
Hi, I would like to suggest a warning flag to elements where height<min_height ([example](https://www.openstreetmap.org/way/914430676)) and building:levels<building:min_levels ([example](https://www.openstreetmap.org/way/172508399)).

**Comment by Famlam** [comment]
it seems the first example lacks `min_*` keys?

I found this ticket in JOSM for min_height:
https://josm.openstreetmap.de/ticket/21286
(I.e.: if we add it, restrict to building(:part) )

**Comment by Famlam** [comment]
Has been merged in JOSM, so we should update the mapcss soon

**Comment by Famlam** [comment]
I just realized that JOSM used the `area` syntax in their rule, which Osmose doesn't support.
I'll create a new file with all workarounds for rules that are valid, but unfortunately not supported (yet) by Osmose. (E.g. `area` -> `way:closed` (and appropriate extra selectors where needed) and - if common - `relation[type=multipolygon]`)

**Comment by Famlam** [comment]
@frodrigo I dived into the code of JOSM for a bit and it seems `area` in mapcss is equal to
```
way[area=no], relation[type=multipolygon]
```

I.e. 
```
area[building] {
  throwWarning: "I am a building";
}
```
equals
```
way[area!=no][building]
relation[type=multipolygon] {
  throwWarning: "I am a building";
}
```

See: https://github.com/JOSM/josm/blob/ed783461e7043ddf1ef587aeb3879209fcbb6e1f/src/org/openstreetmap/josm/gui/mappaint/mapcss/MapCSSStyleIndex.java#L145 (filtering of `area=no`)
and 
https://github.com/JOSM/josm/blob/ed783461e7043ddf1ef587aeb3879209fcbb6e1f/src/org/openstreetmap/josm/gui/mappaint/mapcss/Selector.java#L796-L809 (rewrite of `area` to multipolygons and ways)

Can't we just rewrite `area` rules as such instead of discarding them? Am I missing something here?

**Comment by Famlam** [comment]
All seems deployed. Here's the error for the initial post:
https://osmose.openstreetmap.fr/nl/issue/551f21e9-4e9c-be8c-cb03-89cb5618caec
