### ISSUE TITLE
Add more imcompatible: picnic

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#1985]
Add imcompatible tags to TagRemove_Incompatibles.py
* leisure=picnic_table + tourism=picnic_site

**Comment by Famlam** [comment]
Maybe better to add this ([and the other hardcoded combinations](https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagRemove_Incompatibles.py#L124-L128)) to the [mapcss rules](https://github.com/osm-fr/osmose-backend/blob/dev/plugins/TagFix_MultipleTag2.validator.mapcss) so that they can be loaded into JOSM too?
