### ISSUE TITLE
Getting false flag warning for rivers and streams that end in desert, ground and scree piles.

### ISSUE THREAD

**Issue by sekerob** [osm-fr/osmose-backend#2032]
Although [waterway=stream_end](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dstream_end) is present on the last node, Osmose reports the natural flow as being unconnected. JOSM will stop flagging this during validation if the tag has been affixed.

**Comment by Famlam** [comment]
Do you have an example dataset?

**Comment by sekerob** [comment]
Since I give them the routine 'false positive' treatment done a fresh one this morning which I'd expect to get a pin sometime early tomorrow.

https://www.openstreetmap.org/changeset/141723339#map=13/42.4441/13.6598

node 11217536366

When removing the tag, the JOSM message is "Waterway ends without a connection to another waterway or the direction of the waterway is wrong id 11217536366. Add the tag back and JOSM is senang,

(Sorry for putting this in the wrong place. How this landed in the wrong repository I don't know as clicked thru from Osmose backend)

**Comment by Famlam** [comment]
> Since I give them the routine 'false positive' treatment done a fresh one this morning which I'd expect to get a pin sometime early tomorrow.

Before doing so tomorrow, please send us the item and class number of the error so we can easily pin down the issue :).
I suspect item 1220 class 3

> And osmose should stop warning about that once the tag has been added on the node.

Agree.

**Comment by sekerob** [comment]
"Before doing so tomorrow.... "

That's why I mapped a fresh 'hands off' one :O))) (In fact mapped a bunch, the whole Campo Imperatore is innundated with those, These particular ones disappeared into water saturated heath like covered ground and then miles many miles many pop up as natural springs  You'll find the 'Fonte xyz' all over the place.

**Comment by frodrigo** [comment]
I'm unsure about this. The water go somewhere to a natural=sinkhole or a waterway=soakhole or other natural or not feature.

Is not like a no_exit for highway.

**Comment by Famlam** [comment]
I can imagine a few scenarios where it would apply, for example from a mountain (hard rock) onto a long stretch of porous soil where it just infiltrates into the ground water (without clear flow direction) until the point where it's all evaporated/infiltrated. Or a very thin intermittend stream of mountain water which just flows downhill until it evaporates (because the soil is warm and it's too little water to reach a main river). In those cases, this tag would just indicate the maximum distance the water ever travels.
p.s. for what it's worth, JOSM supports it too https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/geometry.mapcss#L373

**Comment by Famlam** [comment]
The fix is live on Osmose :)
(I can't show you the graph as you already marked them as false positives, but new ones shouldn't appear anymore)
