### ISSUE TITLE
Wrong voltage suggestion for réséda network

### ISSUE THREAD

**Issue by Jean-BaptisteC** [osm-fr/osmose-backend#2038]
https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_power_substation_minor_FR.py#L30
This analysis suggest 20 000 volts for minor_distribution this voltage is used by Enedis
But other operator use different voltage, in my case réséda use 17 500 volts

**Comment by frodrigo** [comment]
cc @flacombe

**Comment by Jean-BaptisteC** [comment]
I think the best way is to enumerate operator with voltage different of Enedis,
ORE Agence can be this information ?

**Comment by flacombe** [comment]
20000 volts is [the default value](https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000021896673) for medium voltage in France, that's why we use it in Osmose.

Voltage actually depends and varies at each medium voltage bay in distribution substations, as show on [capareseau](capareseau.fr) website for each substation.
There is no voltage per operator, such a list doesn't exist.
It can be changed [in the middle of a line](https://www.openstreetmap.org/node/11223302887) in the country.

As we don't have open data for voltages of each line, it' not possible to automatize osmose on this tag.
However if you are knowledgeable about a given area, it is possible to set a particular voltage, see what was done near of Falaise https://openinframap.org/#11.26/48.8544/-0.3231

**Comment by Famlam** [comment]
I'm just thinking, if the voltage is unknown from the open data set, it may be better to not give an explicit value in a fix proposal (but e.g. describe it in the sidebar text). Otherwise it's likely people will assume the 20000 is known to be correct from the open data and add it to OSM?

**Comment by flacombe** [comment]
It would be good to move `voltage=20000` from static1 to static2 in this analyzer, just like `substation=minor_distribution` we are unable to define from opendata currently.

Data will come, maybe.

**Comment by Famlam** [comment]
I never worked on the merge analysers, so I don't know what exactly this changes, but if I look at the output it seems they're just merged, e.g. for the user nothing would change, correct?
![image](https://github.com/osm-fr/osmose-backend/assets/1315520/a3a2476f-475d-4670-917c-8ec86c8995ac)

**Comment by frodrigo** [comment]
@flacombe why do you want to set `voltage` if unknown ? We can just remove it.

**Comment by flacombe** [comment]
> for the user nothing would change, correct?

Putting `voltage=20000` in static2 won't produce additional warnings when user will define another voltage (like 17500) when applicable.

> @flacombe why do you want to set voltage if unknown ?

Because it is really important to allow distinction with other substations with higher voltage.
The most common term would be `voltage=medium` or `voltage=hta`  but it's a mess to process with math expressions.
As the default value is define by law, we just use it waiting for more extensive data.

**Comment by Famlam** [comment]
> Because it is really important to allow distinction with other substations with higher voltage.

Hmm, I would still be in favor of not proposing a value if it's unknown. I would argue a missing value is less bad than a wrong value.

But as an intermediate solution: how about giving multiple fix suggestions, like voltage=17500, voltage=20000, voltage=25000. In that way it'll be more clear for the user that it's not a fact that's proposed, just a possibility. (Not sure if Merge analysers support this)

And definitely static2 then :)

**Comment by frodrigo** [comment]
> (Not sure if Merge analysers support this)

Not implemented yet.

**Comment by flacombe** [comment]
> how about giving multiple fix suggestions, like voltage=17500, voltage=20000, voltage=25000.

It's not suitable here since the mapper isn't able to find the information at all (it's not readable on ground).

Data has been asked to operators a few days ago to reduce the amount of undetermined voltages.
https://www.agenceore.fr/forum-expert/tension-dexploitation-des-reseaux-hta

PR for static2 is on its way.

**Comment by frodrigo** [comment]
> PR for static2 is on its way.

I merged it, as minimum requirement change.

Rather than just a wrong voltage, maybe add a note tag to let know that the voltage is uncertain, but high.

**Comment by Jean-BaptisteC** [comment]
I think it can be closed for now, we can't doing more things for now
