### ISSUE TITLE
`indoor=door` without `level` or `repeat_on`, for doors part of a `indoor=room` way

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-backend#2039]
I was wondering about [these issues](https://osmose.openstreetmap.fr/nl/map/#zoom=18&lat=51.84688&lon=5.870524&item=2120&level=1%2C2%2C3&tags=&fixable=), all warning: `indoor=door without level or repeat_on`
item 2120 - class 21201

Example: [issue](https://osmose.openstreetmap.fr/nl/issue/feece0c7-2d10-746b-afa1-cb1d35f2b0a8) about [this node](https://www.openstreetmap.org/node/10971373641) which is connected to [this way](https://www.openstreetmap.org/way/1181400043)

Here, this `indoor=door` node is part of a `indoor=room` way with a `level` key. Is it than necessary to also tag `level` on the door? I think that's implied from the way it's connected to, meaning it's redundant to tag it again on the door?

(It would be similar to copying the `layer` tag of a highway onto all it's connected `highway=traffic_signs` and `traffic_calming=*`, something that's not done either as it's implied to be part of the way)

@nlehuby any thoughts on this? Should this warning be adjusted or is this correct?

**Comment by nlehuby** [comment]
It works on some simple cases, but it's not always easy to guess the level of the door. For instance
- if it's at the end of a highway=steps or highway=ramp serving several levels (in this case, you need to calculate the level of the door node on the understanding of the staircase's tags and draw direction). For ex : can you guess the level of this entrance https://www.openstreetmap.org/node/5926452947
- if it is on an elevator with several doors (in this case, the level cannot be deduced at all). For ex: the 2 doors of this room https://www.openstreetmap.org/way/1091312309
- if it serves rooms or areas that are multipolygons (in this case, the level will not be indicated on the way to which the node belongs, but on the relation that includes this way). Fox ex : the doors of this way https://www.openstreetmap.org/way/993951772

And sometimes (although I think it should be avoided), we may have a node that is shared between several levels, like this door https://www.openstreetmap.org/node/4133664748, which belongs to these two polygons (https://www.openstreetmap.org/way/994004805 & https://www.openstreetmap.org/way/993951783) even though it's actually only on level 0

Generally speaking, I think that as soon as levels are indicated, it's better to add them on all indoor objects, because it can quickly become complex to understand the layout.
