### ISSUE TITLE
Exempt power=line from Name_Multiple.py

### ISSUE THREAD

**Issue by emersonveenstra** [osm-fr/osmose-backend#2049]
According to [this changeset comment](https://www.openstreetmap.org/changeset/138561947), it is okay for `power=line` ways to have two names depending on the connecting substations. This appears to be currently about 9% of all named `power=line` ways from overpass-turbo:

`way["power"="line"]["name"~";"]` gives 4128 results
`way["power"="line"]["name"~"/"]` gives 3463 results
`way["power"="line"]["name"]` gives 88923 results

I'm not sure if this is enough to give an exemption or not, but thought i'd raise this issue just in case.

**Comment by frodrigo** [comment]
cc @flacombe

**Comment by flacombe** [comment]
Multiple names on `power=line` is a temporary workaround waiting for [routing proposal](https://wiki.openstreetmap.org/wiki/Proposal:Power_routing_proposal) to be reviewed.
Each power line should have only one origin and only one end. We are currently using `name` to give the name of supported circuits (just like if we use `highway=primary` names to state bus lines names on it) instead of the line.

Solution is to map power circuits with an appropriate relation: https://www.openstreetmap.org/relation/6106033

So I'm in favour to keep the warnings.

**Comment by emersonveenstra** [comment]
thanks for the clarification! i'll close this issue then
