### ISSUE TITLE
lanes with conditionals should be accepted (item  3160 class 31601)

### ISSUE THREAD

**Issue by kaligrafy** [osm-fr/osmose-backend#2126]
As seen in the [lanes official wiki](https://wiki.openstreetmap.org/wiki/Key:lanes) (see lanes:bus/psv), lanes conditionals can have non integer values like "lanes:bus:conditional=1 @ (Mo-Fr 07:00-19:00)" but right now osmose issues an error (item 3160 class 31601)

It should not trigger an error.

**Comment by Famlam** [comment]
> lanes:bus=1 @ (Mo-Fr 07:00-19:00)

Your example misses the `:conditional` suffix, so no conditional expression is expected. 

---

However, the issue is valid, for example with https://osmose.openstreetmap.fr/nl/issue/1215f1fe-1fec-164a-f644-b5ae5b95c8df

Item 3160 / class = 31601
`Bad lanes value`
`lanes=0 @ 22:00-05:00 is not an integer`
For `lanes:bus:conditional = 0 @ 22:00-05:00`

**Comment by kaligrafy** [comment]
Fixed the issue comment to add the missing conditional 👍

**Comment by Famlam** [comment]
It was quite effective in reducing the number of issues:
https://osmose.openstreetmap.fr/nl/issues/graph.png?item=3160&class=31601&start_date=2024

Thanks for reporting!
