### ISSUE TITLE
Not sure why we do not want to keep oneway=true on roundabouts to minimize risk of routing errors

### ISSUE THREAD

**Issue by kaligrafy** [osm-fr/osmose-backend#2128]
source | 415768
item | 4020

Roundabouts have the tag oneway=yes implicit by default, but some actual or future osm parsers could ignore the junction tag and could route cars in the opposite direction in roundabouts. I suggest that, at least, osmose should not trigger a warning/error when oneway=yes is added to a roundabout for security reasons. In the Montreal area, we specify the oneway=yes in every roundabouts for this reason, not for duplication, but to make sure actual and future routing engines would not route cars in the opposite direction. I would suggest that osmose accept this tag and not trigger an error.

**Comment by ComradeRamen** [comment]
If your routing engine routes improperly you should fix your routing engine. This has the same vibe as your idea to add pseudo-highways at sharp corners where there's no separation or splitting highway links at the beginning of the merge instead of at the gore. Your propensity to ignore established conventions of OSM is not appreciated on my part.

**Comment by frodrigo** [comment]
Keeping `oneway=true` is harmless, but unnecessary. It was here for historical reason in Osmose. Today we does not add kind of issues report.

But unsupported `junction=roudabout` in routing engine is definitive not a good argument, as it is one of the basic tag of OSM.
