### ISSUE TITLE
Update data for analyser_merge_charging_station_FR

### ISSUE THREAD

**Issue by XioNoX** [osm-fr/osmose-backend#2156]
Hi,

Similar request to what happened in https://github.com/osm-fr/osmose-backend/issues/1621

The current data is 1.5 years old, would it be possible to update it to something more recent ? Maybe by automatically fetching the data from data.gouv.fr ? For example the `Export au format geojson (v2.3.1)` as this resource URL seems stable since "26 juillet 2022".
Or https://github.com/BastienGauthier/clean_french_irve/tree/main/data (found in https://www.data.gouv.fr/fr/datasets/fichier-consolide-des-bornes-de-recharge-pour-vehicules-electriques/#/community-resources )

Cheers,

**Comment by frodrigo** [comment]
Ping @nlehuby @PanierAvide

**Comment by nlehuby** [comment]
I'm not sure to understand your request @XioNoX : on what basis do you say that the dataset has not been updated since July 2022?

The current data is from 20240206 (~ a month old). And the schema has not changed, still version 2.

So the current state seems satisfactory.

That said, if you've identified a file with more info or things that aren't managed yet, feel free to add details here or to upgrade the Osmose analysis...

**Comment by XioNoX** [comment]
I guess I got put off by the  `millesime="05/2022"` in https://github.com/osm-fr/osmose-backend/blob/dev/analysers/analyser_merge_charging_station_FR.py#L63
Combined with some more recent data is incorrect or missing in that CSV (for example some stations got renamed to Freshmile in Brest, France).
It's probably fine to close the ticket, or clarify the update frequency in or around the CSV used here.

**Comment by nlehuby** [comment]
I've updated the doc to clarify the update frequency and list the cleaning processes done in the file used : https://github.com/Jungle-Bus/ref-EU-EVSE/blob/master/README.md
