### ISSUE TITLE
False positive: newlines in inscription=*

### ISSUE THREAD

**Issue by unnervingduck** [osm-fr/osmose-backend#2302]
Osmose flags the linefeed characters in the inscription textfield as non-printable. The wiki page suggests `|` or slashes `/`, but this approach is problematic because real objects might contain those symbols.

Initially reported this as a [bug on iD editor,](https://github.com/openstreetmap/iD/issues/10326) but I was referred here. 

Example node:
https://osmose.openstreetmap.fr/en/issue/cf0b4bd8-30b6-9aa4-b0e9-15e9c2894a27

**Comment by frodrigo** [comment]
item 	5070
class 	50702 
https://github.com/osm-fr/osmose-backend/blob/master/plugins/Name_Script.py#L48

**Comment by Famlam** [comment]
Perhaps you can first update the wiki to reflect that actual newlines may also be used?
(Support definitely seems to vary per editor. In JOSM I'm unable to use a newline it seems, and if I modify the inscription the newline will be dropped, so it's probably best to first update the wiki, then get support from the major editors; otherwise negative side effects may arise where newlines get lost altogether, rather than remain as a pipe or slash character)

**Comment by Famlam** [comment]
Warnings about newlines in values have been removed :)
