### ISSUE TITLE
"Initial stuck to the name" - should be OK if Name Suggestions Index says so?

### ISSUE THREAD

**Issue by osm-spiregrain** [osm-fr/osmose-backend#2399]
- the item and class number: 5010 / 902
- a permalink to the Osmose map:  https://osmose.openstreetmap.fr/en/issue/8d0187de-b373-dfdc-c53f-6bf35dd9cf02

Small point, but Osmose and NSI (as used for iD name suggestions) get into a fight when the name in NSI fails the "Initial stuck to the name" check.   NSI has the name "H.Samuel", Osmose would prefer "H. Samuel".   Should Osmose ignore "Initial stuck to the name" and similar name checks when NSI is asserting a different standardised name when if there is a brand:wikidata set?    

Maybe this particular problem (H.Samuel/H. Samuel) should be fixed by fixing the NSI- but should Osmose skip these checks if there is a brand:wikidata set?

![image](https://github.com/user-attachments/assets/12552f42-4b5d-4f57-b7b4-b1b3b1757c10)

![image](https://github.com/user-attachments/assets/156fab58-0063-4310-bff1-a6e532885952)

**Comment by Famlam** [comment]
Although we can technically couple NSI to a whitelist in the plugin (we do that in other plugins as well), I think here the NSI is wrong, because also the [website of that shop](https://www.hsamuel.co.uk/) lists it with a space in most places, e.g. 
![image](https://github.com/user-attachments/assets/65dd3726-ddd7-4c56-8c1d-cef23472ebd8)
![image](https://github.com/user-attachments/assets/23e729d3-fde8-41a6-a413-b72d640b6a0c)

I see you already contacted them:
https://github.com/osmlab/name-suggestion-index/issues/10171

**Comment by osm-spiregrain** [comment]
Yes - if you read on, the shop doesn't seem to be very clear about it - they use both "H. Samuel" and "H.Samuel" on their website.   I've suggested the NSI adopt the space.   

My question for the osmose-backend maintainer/contributors is whether NSI entries should _in general_ override 5010 / 902 and similar checks.   I hadn't thought of the term 'whitelist', but that's exactly what I meant - so thank you.

**Comment by frodrigo** [comment]
I think this check should be country dependent.

**Comment by Famlam** [comment]
Fix deployed, about 5000 cases less worldwide :)
