### ISSUE TITLE
Update French Power generator

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#510]
I update the OpenData for power generator.

**Comment by frodrigo** [comment]
I have update the OpenData merge for Generator
https://github.com/frodrigo/osmose-backend/blob/master/analysers/analyser_merge_power_generator_FR.py

@flacombe please can your review the data and the use of the data in the code, please?

**Comment by flacombe** [comment]
Nice you had done this update
Here is the current situation for French *plants* registry :
* ''old'' 2017 version (the one you use) : https://opendata.reseaux-energies.fr/explore/dataset/registre-national-installation-production-stockage-electricite-agrege-311217/information/?disjunctive.departement&disjunctive.region&disjunctive.libelletension&disjunctive.libelle_filiere&disjunctive.libelle_combustible&disjunctive.libelle_combustible_secondaire&disjunctive.libelle_technologie&sort=codeinseecommune&q=VIllarodin
* ''New & unavailable'' 2018 version : https://opendata.reseaux-energies.fr/explore/dataset/registre-national-installation-production-stockage-electricite-agrege/information/

This is a file consistent with power=plant in OSM, not power=generator (you got a single line for facilities containing several generator)
Osmose should look for corresponding power=plant, not power=generator

Additionally I'd recommend to use columns 'codeFiliere', instead of 'Filiere', only which is consistent to OSM plant:source.

Columns 'voltage', 'codeTechnologie' will be useful to tag corresponding generators in the plant (which will deserve its own dedicated analysis). Voltage shouldn't be used on power=plant objects

**Comment by frodrigo** [comment]
The 2018 version have metadata info...but not the data.
Ok. I rename all to plant
https://github.com/frodrigo/osmose-backend/blob/master/analysers/analyser_merge_power_plant_FR.py

**Comment by flacombe** [comment]
Thank you
I've added comments directly on the commit

Will you use codeFiliere or you wish to stay with filiere instead?

**Comment by frodrigo** [comment]
I stay with Ifiliere, the code is already done.

**Comment by flacombe** [comment]
Ok
I hope it's stable values

We'll see when 2018/2019 version will be back online (after a little cleanup)

**Comment by frodrigo** [comment]
Results expects here: http://osmose.openstreetmap.fr/en/errors/?item=8270&useDevItem=all

**Comment by frodrigo** [comment]
Result are here.

Note: this fix still not integrated https://github.com/frodrigo/osmose-backend/commit/2f53d17787f9249252cdb7b5ce778d90ab506153
Note: the item is still hidden 

Need to add an explanation about the level of detail of localisation.

**Comment by flacombe** [comment]
Indeed, sounds like markers are placed at the center of the village
http://osmose.openstreetmap.fr/en/map/#item=&useDevItem=all&zoom=16&lat=44.63113&lon=3.89896&level=3&tags=power&fixable=

And personal information are sometimes used to name the plant, like here : http://osmose.openstreetmap.fr/en/map/#item=&useDevItem=all&zoom=17&lat=44.451359&lon=2.79264&level=3&tags=power&fixable=
It sounds weird such a plant outputs 59 MW, are you sure about the plant:output:electricity ?

I think plants < 1 MW should be avoided on osmose.
IMHO it's not desirable to add domestic facilities (but I may be wrong)

**Comment by frodrigo** [comment]
Ok values in the data are in KW, not in MW.
If I cut on 1 MW I will keep 3 533 rows on 36 330.

**Comment by flacombe** [comment]
Many of < 1 MW plants are domestic PV installations.

You may filter wind and PV facilities only.

**Comment by frodrigo** [comment]
Data is updated on Osmose. Please can you check again the results.

**Comment by flacombe** [comment]
Thanks
As far as i know, results sounds ok
Hope that further versions of the file will provide coordinates to get a better view with features with right position

**Comment by frodrigo** [comment]
The filter for 1KW was not good. I fixed it, we have to wait for the results.

**Comment by frodrigo** [comment]
Now filtered data are available on Osmose frontend.

**Comment by flacombe** [comment]
Thank you Frédéric, that's great

See you in Montpelier by this weekend

**Comment by frodrigo** [comment]
Added some fuzzy to the location to avoid markers overlap and see all markers by municipality.

@jocelynj we can enable this item 8270
