### ISSUE TITLE
not accept addr:housenumber=snc 

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#531]
@dieterdreist https://github.com/osm-fr/osmose-backend/commit/30df15ba73d3144c0f03a2dc0151890616a09d48#commitcomment-33887341

> We should not accept addr:housenumber=snc because “snc” is not a housenumber. Please revert this. By the way, there is a recent proposal for nohousenumber=yes which is describing this situation.

https://wiki.openstreetmap.org/wiki/Key:nohousenumber

**Comment by frodrigo** [comment]
@dieterdreist where is the proposal?

I suggest do nothing until the proposal is validated (or no).

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Jun 2019, at 13:09, Frédéric Rodrigo <notifications@github.com> wrote:
> 
> @dieterdreist where is the proposal?
> 

I have to excuse, I was remembering wrong, apparently there isn’t a proposal, I had added documentation of the tag directly into the wiki tag space in this case.

AFAIK the nohousenumber tag is not disputed, and the feedback on talk-it was only positive.

> I suggest do nothing until the proposal is validated (or no).
> 


you have already done something, you added a rule for addr:housenumber, so that something which isn’t a housenumber, will not raise an issue. This is not strictly related to the tag which says there isn’t a housenumber, it would be wrong also in the case that a proposal for nohousenumber or another tag would fail. I mainly wanted to point out to you that this is the case.

Maybe I will make a proposal for this (actually for you ;-) ), but it isn’t on my urgency list.



Cheers,
Martin

**Comment by frodrigo** [comment]
We can not support on Osmose a just created tag with 10 objects in the database with no vote on it.

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Jun 2019, at 18:40, Frédéric Rodrigo <notifications@github.com> wrote:
> 
> We can not support on Osmose a just created tag with 10 objects in the database with no vote on it.
> 

yes, this is completely understandable

I’m sure adoption would grow faster if you marked the addr:housenumber=snc error as error though. In theory none of this should exist anyway, every entrance should have a housenumber according to legislation.

Cheers, Martin

**Comment by frodrigo** [comment]
Reopen if required.
