### ISSUE TITLE
Have a check that finds extranious nodes in buildings

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#588]
A building may have nodes in it which have no tags and have a 180 degree angle (straight line).  [Angle could be maybe 178-182 degrees] These nodes are useless and can be removed.  This is a clue that the building is drawn incorrectly.  Especially if the angle is not exactly 180 degrees... this means the building is not square.

The red dot in the below example

![image](https://user-images.githubusercontent.com/26171839/63212547-3ec1d180-c0d4-11e9-8f1a-4407b6658e8d.png)

**Comment by frodrigo** [comment]
Will not do this. It's minor improvement not issues with the data.

Checking millions of building will be time consuming.

Small deviation accumulated can make circle.

**Comment by matthewdarwin** [comment]
FYI, apparently a lot of people care about having perfect buildings.  See very long thread here, as an example: https://lists.openstreetmap.org/pipermail/talk-ca/2019-January/thread.html

**Comment by frodrigo** [comment]
About Canadian import I personally think there is already other major issues. Have you already seen https://twitter.com/osmose_qa/status/1130217322420101121 and https://twitter.com/osmose_qa/status/1130216908240953349.

But there is a bigger item, disabled for Canada, because is overflow Osmose of bad water ways : 
* http://osmose.openstreetmap.fr/en/errors/graph.png?country=canada*&item=1220
* https://github.com/osm-fr/osmose-backend/blob/master/osmose_config.py#L808

**Comment by matthewdarwin** [comment]
Lots of issues from previous CanVec imports where the interpolations/forest/rivers/etc are imported in squares.  You can see the overlapping nodes overlap in a grid pattern.   There needs to be an automated script to merge all these things.

![image](https://user-images.githubusercontent.com/26171839/63227130-63d84200-c1b1-11e9-81df-6a72934764d5.png)
