### ISSUE TITLE
Parking "Object tagged twice as way and relation" seems false positive

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-backend#590]
Someone else provided this explanation, I am filing a report based on their information:

It looks like a false positive because `site=parking` requires `amenity=parking` but can't have `amenity=parking` on relation.

https://wiki.openstreetmap.org/wiki/Relations/Proposed/Site#Tagging
https://wiki.openstreetmap.org/wiki/Proposed_features/parking#Tag_overview

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=45.481263&lon=-75.527589&item=4080&level=1%2C2&tags=&fixable=

http://osmose.openstreetmap.fr/en/error/31013084779
http://osmose.openstreetmap.fr/en/error/31013084776

**Comment by frodrigo** [comment]
Why it would be a false positive?
The parkings are tagged twice, aren't?

**Comment by james2432** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking
amenity=parking is not allowed to be in a relation

So if you want to tag a parking spot with a relation and tag individual spots
type = site
is required. but a site relation needs a definition of what amenity it is inside the relation:
https://wiki.openstreetmap.org/wiki/Relations/Proposed/Site
as well as site=parking

so you have a catch-22 because amenity=parking can't be tagged in relation(nor does it render), but the site specification requires it in the relation

**Comment by grischard** [comment]
In that case, don't tag the parkings with the name, and don't tag the site as parking?

**Comment by Marc-marc-marc** [comment]
I use a multipolygon relation for this case, in stead of the (proposed) parking site relation.
it allow to put the amenity=parking only once on the relation

**Comment by frodrigo** [comment]
Please, reopen if required.
