### ISSUE TITLE
Detect closed power=line

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-backend#595]
Sometime there is misusage of power=line

https://www.openstreetmap.org/way/379565306

cc @flacombe

**Comment by flacombe** [comment]
Hi and thank you for notice

I agree that power=line should be used on closed polygons
https://wiki.openstreetmap.org/wiki/Tag:power%3Dline

There can be kilometers-wide topologies that involve power line rings. Then they should be mapped as at least two sections of not closed lines since there is certainly switching equipment on the ring to operate the network.

All the best

**Comment by frodrigo** [comment]
New MapCSS rule should be done about this.

**Comment by frodrigo** [comment]
@Klumbumbus do you want to support detection of powerline loop in JOSM MapCSS ?

**Comment by Klumbumbus** [comment]
I see potential false positives, e.g. https://www.openstreetmap.org/way/215832895.

https://overpass-turbo.eu/s/Z7J

**Comment by flacombe** [comment]
@Klumbumbus Thank you for this example.
It's not a false positive: such power lines shouldn't be mapped as a closed triangle but as 3 independent ways.
Detecting them is particularly useful.

An equivalent situation is here in France : https://www.openstreetmap.org/way/135314795
Have a look to overlying relations and necessity to have 3 independent segments

**Comment by Klumbumbus** [comment]
>It's not a false positive: such power lines shouldn't be mapped as a closed triangle but as 3 independent ways.

But in this case there are no relations and I don't really see a reason why it should be wrong in this case.

**Comment by flacombe** [comment]
There are no relations because network is currently lightly mapped.
At the end, every high voltage power line will be member of a relation because power is flowing over them
https://wiki.openstreetmap.org/wiki/Proposed_features/Power_routing_proposal

It's mainly wrong here because probability to find closed wires in triangle there is very low.
Usually you have 3 incoming 2 circuits power lines and they splits like my French example.

**Comment by Klumbumbus** [comment]
OK, we can give it a try. However I guess it should not warn in case of line=busbar. This one is mapped correctly, isn't it? https://www.openstreetmap.org/way/639817007

**Comment by flacombe** [comment]
No this busbar isn't mapped correctly neither.

Such a polygon should be mapped with power=switchgear as it encloses several busbars
https://wiki.openstreetmap.org/wiki/Tag:power%3Dswitchgear

Here (according to aerial imagery), busbars are on the east and on the west sides.
north and sounth are power=bay only (separated from busbars by disconnector switches)

Busbars may have several shapes but are most often lines and not polygons
https://openinframap.org/#16.99/47.324871/4.687416

**Comment by Klumbumbus** [comment]
Added in JOSM in https://josm.openstreetmap.de/changeset/17249

**Comment by frodrigo** [comment]
Tank all.
