### ISSUE TITLE
Change sensitivity of parking-access-route QA

### ISSUE THREAD

**Issue by tordans** [osm-fr/osmose-backend#626]
This is more a question than an issue. Maybe a suggestion.

Example: http://osmose.openstreetmap.fr/en/map/?#zoom=17&lat=52.486714&lon=13.454741&item=1010%2C1040%2C1050%2C1060%2C1070%2C1080%2C1090%2C1100%2C1110%2C1120%2C1140%2C1150%2C1160%2C1170%2C1180%2C1190%2C1200%2C1210%2C1220%2C1221%2C1230%2C1240%2C1250%2C1260%2C1270%2C1280%2C2010%2C2020%2C2030%2C2040%2C2060%2C2080%2C2090%2C2100%2C2110%2C2120%2C2130%2C2150%2C2160%2C3xxx%2C4xxx%2C5020%2C5030%2C5040%2C5050%2C5060%2C5070%2C5080%2C6xxx%2C7xxx%2C8xxx%2C9xxx&level=1%2C2%2C3&tags=&fixable=

There is an `amenity = parking` right next to the street. 
The issue says "Missing access way to parking". 

My understanding is, that one would not add a (very small) way that connects this area with the way, since it is so near to the way, that a router would be able to handle it.

Also, I don't think there is a preference to "glue" those parking-areas to the way (is there?).

My suggestion is, to make this QA rule a bit less sensitive so it maybe only marks areas that are more than 100 meters (?) away from the next way.

**Comment by matthewdarwin** [comment]
There are lots of these errors in my area too... I had not looked into what to do about them yet.  CC @zzptichka

**Comment by zzptichka** [comment]
If it was up to me I would leave warning 1 and remove warnings 2 and 3.

![image](https://user-images.githubusercontent.com/29608734/65445645-b46e3b00-de00-11e9-8275-d2f2d36a867e.png)

**Comment by tordans** [comment]
What do you guys think about …

> My suggestion is, to make this QA rule a bit less sensitive so it maybe only marks areas that are more than 100 meters (?) away from the next way.

(Is such a change even possible?)

**Comment by ferdinand0101** [comment]
I belive that it's more important to look weather the parking is paralel to a road like in 2 and 3 which is not the case in 1

**Comment by ferdinand0101** [comment]
Your option @tordans is definitely possible

**Comment by zzptichka** [comment]
I think 100 meters is a bit too far. Maybe something more like 30 meters.

**Comment by frodrigo** [comment]
May be just filter by parking area?

**Comment by maro-21** [comment]
I agree.
We should either remove this issue or change its sensitivity beacuse 30% of all issues in my area is "Missing access way to parking" where 95% are false positives.

**Comment by ferdinand0101** [comment]
about changing the sensitivity in my experience most of those issues apper on "small" spaces as such I'd suggest a minimum lenght for this issue.
100m ?

**Comment by matthewdarwin** [comment]
@zzptichka any further comments on this one?

**Comment by maro-21** [comment]
The best example:
http://osmose.openstreetmap.fr/en/map/#item=3161&zoom=16&lat=51.15494&lon=16.89976&level=1%2C2%2C3&tags=&fixable=

**Comment by Bibi56** [comment]
> The best example

Best example of a poor parking description? :-(
OSM is not designed as a drawing tool but as a mapping tool ;-).
I mean here it would be better to have used tags describing the street usage: [parking:condition](https://wiki.openstreetmap.org/wiki/Key:parking:condition) and [parking:lane:*](https://wiki.openstreetmap.org/wiki/Key:parking:lane), that"s what is right for a "parking [that is] is parallel to a road".
Here I see a confusion between parking and park space. We what to be able to distinguish a parking lot and a parking space.
Otherwise I agree, the check is too sensitive. 10 m would be fine.

**Comment by maro-21** [comment]
> Best example of a poor parking description? :-(

This was the best example for a lot of false positives.

These parking lots are not lanes https://wiki.openstreetmap.org/wiki/File:Parkingonstreetlanes2nowide.png
but they look like this: https://goo.gl/maps/zfj7hzWw7F1E4kj49

**Comment by Bibi56** [comment]
Thanks for the photos. IMHO they are NOT false positive: `parking:lane:both`=`perpendicular` is the correct description for that.
Yes "lane" has an larger acceptance than a road lane.
BTW, it's also less work to describe that way.

**Comment by gdabski** [comment]
The fact that only the Polish details message [here](http://osmose.openstreetmap.fr/en/error/fbbf1796-9991-fe7b-2217-013f6d9c8d8b) refers to supposed false-positives and this thread clearly indicates something.

I second @Bibi56 's view.

**Comment by frodrigo** [comment]
Nevertheless avoiding the check for small parking can avoid the raise of uninteresting issues and make everyone happy with it.

But, I'm agree the parking:lane is also the right way to do for me. But It will not prevent contributors to double map as parking:lanes and parking amenity, not sure if it bad or not.

**Comment by SupaplexOSM** [comment]
There is currently a proposal to differentiate this type of parking: https://wiki.openstreetmap.org/wiki/Proposed_features/parking%3Dstreet_side
(It could also solve the problem discussed here).

**Comment by frodrigo** [comment]
Implement the support of the new `parking=street_side`.
https://wiki.openstreetmap.org/wiki/Tag:parking%3Dstreet_side

**Comment by maro-21** [comment]
I propose to have this issue only for `amenity=parking` with `parking=surface` - these types of parking lots need an access way.

Other types of parking especially recently approved `street_side` should be excluded as well as the other: `lane`, `garage_boxes` and other.

For `amenity=parking`s without `parking=*` the message should suggest to complete `parking=*` instead of drawing a nonexistent road.

**Comment by kymckay** [comment]
I would support @maro-21's suggestion

The strings should definitely make clear that the error may be because `parking=surface` is incorrect too

**Comment by maro-21** [comment]
So, because many street side parkings were tagged `parking=surface` before the tag `parking=street_side` was approved, the message should suggest adding a road or change tagging to `parking=street_side`, `lane` or other.

So maybe sth like this:

```
There should be a `highway` feature leading to this parking facility to allow for correct routing. Add a road or check if `parking=*` is correct.
If it's a street side parking or lane, add appropriate tags.
See [Wiki](https://wiki.openstreetmap.org/wiki/Key:parking) for more information.
```

(an English native speaker should verify grammar)


The script should be only for `parking=surface`.
I would suggest not to have issues for `amenity=parking`s without any `parking=*` because there would be too many of them. There is a StreetComplete task to choose the parking type. So Osmose will work only for Surface parking lots.

**Comment by frodrigo** [comment]
Done here with changes
https://github.com/frodrigo/osmose-backend/blob/master/analysers/analyser_osmosis_parking_highway.py#L72-L75
