### ISSUE TITLE
"Probably only for bottles, not any type of glass" check and especially autofix is unwanted in the Czech Republic

### ISSUE THREAD

**Issue by kudlav** [osm-fr/osmose-backend#691]
Autofix wants to change correct recycling:glass=yes to recycling:glass_bottles = yes

https://wiki.openstreetmap.org/wiki/Osmose/issues#3230
https://osmose.openstreetmap.fr/cs/error/34967455609

According to czech general recycling guide we can recycle:
Coloured glass (used for wine, beer, etc.), smashed glass panes of doors or windows, bottles and jars, broken beverage glass.
See https://jaktridit.cz/en/sorting/sorting-waste-properly---coloured-containers/glass

Simillar to #549

**Comment by frodrigo** [comment]
We can disable it for Czech Republic, or enable where we are sure we can only recycle bottles.
cc @matkoniecz @vinber

**Comment by matkoniecz** [comment]
The problem here is that someone attempted to / defined / wikifiddled `recycling:glass_bottles` to mean "Includes jars but not any of the trickier types listed above under recycling:glass"

tricker glass includes 

> drinking glasses, window glass, light bulb glass, tempered glass, borosilicate glass, Pyrex

I am tempted to invent new `recycling:normal_glass` or to describe `recycling:glass` as excluding tricky glass by default - what should be possible as long as it is normally used in this way. Both require discussion with wider OSM community.

**Comment by kudlav** [comment]
From my point of view 'glass' can be anything containing only pure glass (including bottles) and 'glass_bottles' can be used only for bottles or jars.

This reflects the wiki documentation and best fits to a real system of recycling in our county.

If the glass is not normal, then it's probably not a glass, so 'recycling:normal_glass' looks confusing for me. Maybe I should ask Czech [community](https://www.openstreetmap.cz).

**Comment by vinber** [comment]
In france, in my knowledge, only recycling_type=centre accept all kinds of glass. Always in france, in recycling_type=container it's glass_bottle (bottle, jar and "food glass") it's why osmose analysis, in majority of case, says "I think it's glass_bottle". 

so @kudlav do you think it's better to exclude Czech Republic from Osmose analysis or to apply this analysis only in France ?

**Comment by matkoniecz** [comment]
I checked now situation more thoroughly and discovered, to my surprise, that this validator warning is mostly right in Poland.

It turns out that you are supposed to put there only some types of glass - one used to make bottles and jors. Glassware, pyrex, window glass, glass used to make lighting bulbs, glass from grave candles and more all are not supposed to go into glass container.
 
Fundamental problem here is that organizations responsible for recycling mislabel bins - do not label something "glass" if just one type of glass is supposed to go there!
 
I closed #549 and I will write fore-and-forget note to organization responsible for causing this confusion in my city.

**Comment by ferdinand0101** [comment]
As a German I can say that Germany is like France regarding this

**Comment by frodrigo** [comment]
@kudlav any news on this?

**Comment by tkas** [comment]
Hi, the problem is discussed on talk-cz, but up to now, it seems just disabling this test for CZ is best solution.

**Comment by frodrigo** [comment]
OK. Remove the check for CZ.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/en/errors/graph.png?country=czech_republic_*&item=3230&class=32301

Not working, yet.

**Comment by tkas** [comment]
self.country.startswith("CZ") -> "cz" ? does it try to match czech_republic from:

cz_kraj = gen_country('europe', 'czech_republic',.....

then maybe self.country.startswith("czech_republic") is even better.  Or is it "CZ-XX" from:

cz_kraj("praha", 435514, "CZ-PR")
...

Thanks.

**Comment by frodrigo** [comment]
It should match de code area.

**Comment by frodrigo** [comment]
Cannot work automatically since even the definition of issue was removed for the area.

Cleaned manualy.
