### ISSUE TITLE
`highway=bus_stop` is a bus stop, there is no need to explicitly tag this

### ISSUE THREAD

**Issue by matkoniecz** [osm-fr/osmose-backend#698]
https://osmose.openstreetmap.fr/en/byuser/forteller?username=forteller&item=2140

source	404955
item	2140
class	21411

(1) If this warning has goal to detect invalid `highway=bus_stop` then it would be smarter to check whatever `highway=bus_stop` is attached to `highway=^(service|residential|unclassified|.......)$` line.

(2) If this warning has goal to promote duplicate tagging of `highway=bus_stop` then it would be better to mention this explicitly rather than claim that PTv2 adds useful info.

Or add both - for example, I am more likely to remove PTv2 tagging than to add it so I would certainly disable (2) and I would happily take part in fixing problem in (1). And while (1) is a serious error, (2) is something that is not worth doing manually.

**Comment by frodrigo** [comment]
This come from

https://github.com/Jungle-Bus/transport_mapcss/blob/master/transport.validator.mapcss#L211-L231

Please report to this project.

cc @nlehuby

**Comment by nlehuby** [comment]
yes, `highway=bus_stop` is a bus stop, but the definition of a bus stop is not so clear. Some contributors map them on the side of the street (as a platform) and some map them on the street (as a stop_position). And depending on the editor they used, the stop may or may not be part of the actual way.
the `public_transport = stop_position / platform` tag specifies which of these modeling is used.

This is not about promoting duplicate tagging but about clarifying what we map, especially for data reusers.

This is important because when you map bus stops on the street, you may map only one stop for both directions whereas you will have two stops if you map them on the sides of the street.
BTW, if you can read French, I wrote a small article about that a few years ago : https://nlehuby.5apps.com/mais-je-veux-juste-la-liste-des-arrets-de-bus.html

**Comment by matkoniecz** [comment]
>  the public_transport = stop_position / platform tag specifies which of these modeling is used.

Why checking whatever `highway=bus_stop` is on way representing road is not sufficient? For example `highway=bus_stop` belonging to `highway=residential` is certainly mapped on way (stop_position).

Why tagging this manually would be a good use of time?

**Comment by frodrigo** [comment]
transport.validator.mapcss is defined as a "Uncompromising validation of transit data". Maybe some checks are not adapted to Osmose?

**Comment by matkoniecz** [comment]
For now I opened https://github.com/Jungle-Bus/transport_mapcss/issues/42 and offered to make PR removing this rule.

In case of wontfixing or missing reaction I would recommend blacklisting this check in Osmose as encouraging edits that are neither necessary nor helpful.

**Comment by nlehuby** [comment]
Sorry for the late answer, I was AFK for a few days.

> Why checking whatever `highway=bus_stop` is on way representing road is not sufficient? 

Actually, it is not that simple.
Here are two examples of bus stops that should probably be `public_transport = stop_position` but are not part of a way: https://www.openstreetmap.org/node/2193022778 & https://www.openstreetmap.org/node/5156856821. 
These are mapping errors, but you can find quite a lot of them, probably because some of the tools used to create bus stops (Maps.me, OSMAnd, Jungle Bus, etc ) are not able to properly create a node on a way.

And here are an example of bus stop that is actually part of a way (that even have a `highway=*` tag), but that is a `public_transport = platform`: https://www.openstreetmap.org/node/5775894610

**Comment by matkoniecz** [comment]
>  Here are two examples of bus stops that should probably be public_transport = stop_position but are not part of a way: https://www.openstreetmap.org/node/2193022778 & https://www.openstreetmap.org/node/5156856821.

OK, asking this for nodes very very close to `highway=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|service|living_street` may be defensible.

But I would ask user to move it to a correct position rather than adding tags.

> And here are an example of bus stop that is actually part of a way (that even have a highway=* tag), but that is a public_transport = platform: https://www.openstreetmap.org/node/5775894610

OK, lets be more precise. By "Why checking whatever `highway=bus_stop` is on way representing road is not sufficient?" I meant checking whatever `highway=bus_stop` is in `highway=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|service|living_street` way, being on `highway=platform` way obviously does not mean that it is on a way representing road.

**Comment by nlehuby** [comment]
Ok, so if I want to get the number of bus stops, I need to get all objects with `highway=bus_stop` and then get all ways which they are part of or very close to check if they have `highway=motorway|motorway_link|trunk|trunk_link|primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential|service|living_street`

It's seem at lot of work when we actually have a tag that explicit just that, that has been approved years ago.

**Comment by matkoniecz** [comment]
I would argue that `highway=bus_stop` used to mark things is not a bus stop (in other words it seems to me that `public_transport = stop_position` with `highway=bus_stop` is always a mistake).

And yes, in general to catch mistaggings you need elaborate checks and even this is going to find only some of them.

**Comment by nlehuby** [comment]
From a personal point of view, I agree and I map bus stops as platforms.
But as long as we don't have a approved proposal that tells us that bus stops should always be side to the road or implicitly imply `public_transport=platform` or something like that, this is not a mistagging.

For now, there is no consensus and that `public_transport` tag is the best we have to mitigate the inconsistency that currently exists in our data because we don't have a clear definition of what is actually a bus stop.

**Comment by matkoniecz** [comment]
> as long as we don't have a approved proposal

Untrue, approved proposal is not the only way. Clear consensus is also sufficient.

**Comment by frodrigo** [comment]
Reopen if required.
