### ISSUE TITLE
Allow 'ä' in Luxembourg

### ISSUE THREAD

**Issue by grischard** [osm-fr/osmose-backend#811]
Item and class number: 50701

Link to detail of this marker, from the green "details" links in the popup: https://osmose.openstreetmap.fr/en/error/fea37e71-6006-bbbf-cb78-3f14cdf52dce 

"Park Dräi Eechelen" is the correct name of the place. Having 'äöüë' in a name is normal and expected in Luxembourg. Names can mix both French and German spellings, e.g. the word for "Data" is _Donnéeën_ :)

See also similar false positives in the same area:

https://osmose.openstreetmap.fr/en/error/399fb1bb-3f48-1fbe-a845-785c4f23f55f
https://osmose.openstreetmap.fr/en/error/5b0dfbe3-1b08-fcf2-9efc-0cfe6d070cb1
https://osmose.openstreetmap.fr/en/error/e3110b53-d886-9cd2-f3ee-86d53ee5b374
https://osmose.openstreetmap.fr/en/error/4e1f1909-71bf-87a4-8b47-683be342b7b3
https://osmose.openstreetmap.fr/en/error/399fb1bb-3f48-1fbe-a845-785c4f23f55f

**Comment by frodrigo** [comment]
Done. To be checked.

**Comment by GeWaLu** [comment]
I am wondering if the implementation of the fix for this issue does not have a side-effect on the class 50601 causing new errors from the category "Default and local language name not the same":
I noticed that recently  a bunch of such warnings popped up like 
http://osmose.openstreetmap.fr/en/error/bdce0c41-62c3-1995-527d-72e3ebe708c7
According to https://wiki.openstreetmap.org/wiki/Multilingual_names this combination of names is in my opinion correct for Luxembourg.

Looking at the source code, you changed the default language of Luxembourg to Luxembourgish. This may be ok to check for the character set (as Luxembourgish has as well French as German accents) , but I wonder if this class 50601  does not use the same global configuration and is now confused that the default names is not always in Luxembourgish.

Languages in Luxembourg are quite a complex subject as Luxembourg is multilingual:
- Luxembourgish, German and French are the 3 official languages
- Most default geographical names are in French (What seems also to have been the previous setting of Osmose).
- Some places do not follow the rule (For example only have a Luxembourgish name) and had before false positives due to letters like ä and what seems to have driven this change.

I do not have much experience with the inner workings of osmose... but looking at countries like Switzerland I also wonder if Luxembourg should not also have several permitted languages

**Comment by frodrigo** [comment]
You are right. I recently ask myself if a better option is not to introduce fr_LU (a,d other) support.

**Comment by frodrigo** [comment]
http://osmose.openstreetmap.fr/fr/errors/?country=luxembourg&item=5070&level=1%2C2%2C3

**Comment by frodrigo** [comment]
Lux is now back with fr_LU.
