### ISSUE TITLE
school:FR + kindergarten:FR=

### ISSUE THREAD

**Issue by Shnoulle** [osm-fr/osmose-backend#981]
Hi,

Currently adding amenity:kindergarten + kindergarten:FR=Créche ask to be moved to school ( 7070 ?)

Sample : https://www.openstreetmap.org/way/846591928

Related : https://github.com/osm-fr/osmose-backend/issues/941

**Comment by Olyon** [comment]
Pour une crèche, il n'y a pas de changement, c'est toujours amenity=kindergarten avec la possibilité d'ajouter kindergarten:FR=*
(voir les valeurs possibles ici : https://wiki.openstreetmap.org/wiki/FR:Key:kindergarten:FR?uselang=fr).
Ce sont les écoles maternelles qui migrent de amenity=kindergarten vers amenity=school.

For a "crèche", no change, it is still amenity=kindergarten with the possibility to add kindergarten:FR=*
(see possible values here: https://wiki.openstreetmap.org/wiki/FR:Key:kindergarten:FR?uselang=fr).
It is the "écoles maternelles" that migrate from amenity=kindergarten to amenity=school.

**Comment by Shnoulle** [comment]
Yes i understand but i think if osmose have
`amenity:kindergarten` AND `kindergarten:FR=*` it must be happy :) and don't send an alert.

Must send alert with
`amenity:kindergarten` AND `school:FR=*`
and (maybe)
`amenity:kindergarten` AND `!kindergarten:FR=*`


En FR:
Oui, je comprend mais je pense que osmose ne devrait pas envoyer d'alerte si kindergarten:FR est précisé.
Il devrait envoyer l'alerte si 

1. `amenity:kindergarten` avec `school:FR`
2. éventuellement : `amenity:kindergarten` sans `kindergarten:FR`

**Comment by Olyon** [comment]
Désolé, je n'avais pas compris le problème.
La migration des maternelles de kindergarten vers school, n'a pas encore été faite mais si l'on fait cette modification, sans utiliser osmose, on modifie amenity=kindergarten school:FR=maternelle en amenity=school school:FR=maternelle et on modifie l'analyse osmose pour qu'elle ne s'occupe que des amenity=school et donc plus de signalement sur les amenity=kindergarten sans ref:UAI.

C'est le meme problème que : #126 

Sorry, I didn't understand the problem.
The migration of "maternelles" from kindergarten to school, has not been done yet but if we make this modification, without using osmosis, we change amenity=kindergarten school:FR=maternelle to amenity=school school:FR=maternelle and we modify the osmose analysis so that it only looks amenity=school, there will be no more error on amenity=kindergarten without ref:UAI.

This is the same problem as: #126

**Comment by Shnoulle** [comment]
> C'est le meme problème que : #126

Oui, quasi. C'est la demande de `school:FR`. Je pensais que `kindergarten:FR` aller régler le problème :) avant que 126 soit réglé.

> This is the same problem as: #126

Yes : really near, same with ask for `school:FR`. I think adding `kindergarten:FR` fix the issue before 126 is fixed.

**Comment by vinber** [comment]
> on modifie l'analyse osmose pour qu'elle ne s'occupe que des amenity=school et donc plus de signalement sur les amenity=kindergarten sans ref:UAI.

oui soit on sait (@frodrigo ?) exclure du signalement lorsqu'il y a "amenity=kindergarten AND kindergarten:FR=*", soit on exclut les kindergarten du signalement pour l'instant

> we modify the osmose analysis so that it only looks amenity=school, there will be no more error on amenity=kindergarten without ref:UAI.

yes either we know how to exclude from reporting when there is amenity=kindergarten AND kindergarten:EN=*, or we exclude kindergarten from reporting for the moment
